# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Optional: specify video codec (h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import json
import logging
import os
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

import numpy as np
from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_openarm_follower,
    bi_piper_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    piper_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_piper_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    piper_leader,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STATE, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_bimanual_piper_pair,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos.
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1'.
    vcodec: str = "libsvtav1"
    # Rename map for the observation to override the image and state keys.
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # Path to a JSON file with robot + camera config (e.g. roboclaw manifest.json).
    # When set, overrides robot port and camera CLI args.
    robot_config_file: str | None = None

    def __post_init__(self):
        if self.robot_config_file is not None:
            from lerobot.scripts.robot_config_loader import load_robot_config_from_json

            self.robot = load_robot_config_from_json(self.robot_config_file)

        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")
        sanity_check_bimanual_piper_pair(self.robot, self.teleop)

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    display_compressed_images: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so_leader.SO100Leader
                        | so_leader.SO101Leader
                        | koch_leader.KochLeader
                        | omx_leader.OmxLeader
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    action_feature_names = dataset.features[ACTION]["names"] if dataset is not None else None
    if action_feature_names is None:
        if isinstance(robot.action_features, dict):
            action_feature_names = list(robot.action_features.keys())
        else:
            action_feature_names = list(robot.action_features)

    def vectorize_action(values: RobotAction | None) -> list[float] | None:
        if values is None:
            return None
        return [float(np.asarray(values[name]).reshape(-1)[0]) for name in action_feature_names]

    def vectorize_state(values: dict[str, Any] | None) -> list[float] | None:
        if values is None:
            return None
        return [float(np.asarray(values[name]).reshape(-1)[0]) for name in action_feature_names]

    def vector_distance(left: list[float] | None, right: list[float] | None) -> dict[str, float] | None:
        if left is None or right is None:
            return None
        diff = np.abs(np.asarray(left, dtype=np.float32) - np.asarray(right, dtype=np.float32))
        return {"l1": float(diff.sum()), "linf": float(diff.max())}

    def tensor_to_action_vector(value: Any) -> list[float] | None:
        if value is None or postprocessor is None:
            return None
        raw_value = postprocessor(value)
        if hasattr(raw_value, "detach"):
            raw_value = raw_value.detach().cpu().numpy()
        return np.asarray(raw_value, dtype=np.float32).reshape(-1)[: len(action_feature_names)].tolist()

    def tensor_to_action_sequence(value: Any) -> list[list[float]] | None:
        if value is None or postprocessor is None:
            return None
        if value.ndim == 2:
            value = value.unsqueeze(1)
        return [tensor_to_action_vector(value[:, step]) for step in range(value.shape[1])]

    def vector_distances(
        sequence: list[list[float]] | None, right: list[float] | None
    ) -> list[dict[str, float]] | None:
        if sequence is None or right is None:
            return None
        return [vector_distance(vector, right) for vector in sequence]

    def read_state_before_send() -> dict[str, float] | None:
        if not (hasattr(robot, "left_arm") and hasattr(robot, "right_arm")):
            return None
        state: dict[str, float] = {}
        for side, arm in (("left", robot.left_arm), ("right", robot.right_arm)):
            positions = arm.bus.sync_read("Present_Position", num_retry=2)
            state.update({f"{side}_{motor}.pos": float(value) for motor, value in positions.items()})
        return state

    action_state_debug_fh = None
    action_state_debug_path = os.environ.get("LEROBOT_ACTION_STATE_DEBUG_JSONL")
    include_action_chunks = os.environ.get("LEROBOT_ACTION_STATE_DEBUG_INCLUDE_CHUNKS", "").lower() in {
        "1",
        "true",
        "yes",
    }
    if action_state_debug_path and dataset is not None and hasattr(dataset, "root"):
        if action_state_debug_path.lower() in {"1", "true", "yes"}:
            debug_path = dataset.root / "action_state_debug.jsonl"
        else:
            debug_path = Path(action_state_debug_path).expanduser()
        debug_path.parent.mkdir(parents=True, exist_ok=True)
        action_state_debug_fh = open(debug_path, "a", encoding="utf-8")
        logging.info("[ActionStateDebug] Writing chunk boundary comparisons to %s", debug_path)

    def write_action_state_debug(row: dict[str, Any]) -> None:
        if action_state_debug_fh is None:
            return
        action_state_debug_fh.write(json.dumps(row) + "\n")
        action_state_debug_fh.flush()

    no_action_count = 0
    debug_frame_index = 0
    timestamp = 0
    start_episode_t = time.perf_counter()
    try:
        while timestamp < control_time_s:
            start_loop_t = time.perf_counter()

            if events["exit_early"]:
                events["exit_early"] = False
                break

            obs_t0 = time.perf_counter()
            obs = robot.get_observation()
            obs_processed = robot_observation_processor(obs)
            obs_ms = (time.perf_counter() - obs_t0) * 1000
            infer_ms = 0.0

            if policy is not None or dataset is not None:
                observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

            if policy is not None and preprocessor is not None and postprocessor is not None:
                infer_t0 = time.perf_counter()
                action_values = predict_action(
                    observation=observation_frame,
                    policy=policy,
                    device=get_safe_torch_device(policy.config.device),
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    use_amp=policy.config.use_amp,
                    task=single_task,
                    robot_type=robot.robot_type,
                )
                infer_ms = (time.perf_counter() - infer_t0) * 1000
                act_processed_policy: RobotAction = make_robot_action(action_values, dataset.features)
                robot_action_to_send = robot_action_processor((act_processed_policy, obs))
                action_values = robot_action_to_send

            elif policy is None and isinstance(teleop, Teleoperator):
                act = teleop.get_action()
                if robot.name == "unitree_g1":
                    teleop.send_feedback(obs)

                act_processed_teleop = teleop_action_processor((act, obs))
                action_values = act_processed_teleop
                robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

            elif policy is None and isinstance(teleop, list):
                arm_action = teleop_arm.get_action()
                arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
                keyboard_action = teleop_keyboard.get_action()
                base_action = robot._from_keyboard_to_base_action(keyboard_action)
                act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
                act_processed_teleop = teleop_action_processor((act, obs))
                action_values = act_processed_teleop
                robot_action_to_send = robot_action_processor((act_processed_teleop, obs))
            else:
                no_action_count += 1
                if no_action_count == 1 or no_action_count % 10 == 0:
                    logging.warning(
                        "No policy or teleoperator provided, skipping action generation. "
                        "This is likely to happen when resetting the environment without a teleop device. "
                        "The robot won't be at its rest position at the start of the next episode."
                    )
                continue

            debug_info = getattr(policy, "_last_action_debug", {}) if policy is not None else {}
            should_write_action_state_debug = bool(
                action_state_debug_fh is not None and debug_info.get("is_boundary")
            )
            obs_state_vector = None
            state_before_send_vector = None
            state_before_send_ms = 0.0
            if should_write_action_state_debug:
                obs_state_vector = np.asarray(observation_frame[OBS_STATE], dtype=np.float32).reshape(-1).tolist()
                state_t0 = time.perf_counter()
                state_before_send_vector = vectorize_state(read_state_before_send())
                state_before_send_ms = (time.perf_counter() - state_t0) * 1000

            send_t0 = time.perf_counter()
            _sent_action = robot.send_action(robot_action_to_send)
            send_ms = (time.perf_counter() - send_t0) * 1000

            if should_write_action_state_debug:
                raw_action0_vector = tensor_to_action_vector(debug_info.get("raw_action0"))
                executed_action0_vector = tensor_to_action_vector(debug_info.get("executed_action0"))
                previous_overlap_action0_vector = tensor_to_action_vector(debug_info.get("previous_overlap_action0"))
                robot_action_to_send_vector = vectorize_action(robot_action_to_send)
                sent_action_vector = vectorize_action(_sent_action) if isinstance(_sent_action, dict) else None
                debug_row = {
                    "episode_frame_index": int(debug_frame_index),
                    "elapsed_s_before_sleep": float(time.perf_counter() - start_loop_t),
                    "infer_ms": float(infer_ms),
                    "obs_ms": float(obs_ms),
                    "state_before_send_ms": float(state_before_send_ms),
                    "send_ms": float(send_ms),
                    "queue_len_before": debug_info.get("queue_len_before"),
                    "overlap_len": debug_info.get("overlap_len"),
                    "chunk_overlap_ensemble_prev_weight": debug_info.get("chunk_overlap_ensemble_prev_weight"),
                    "chunk_boundary_bridge_steps": debug_info.get("chunk_boundary_bridge_steps"),
                    "chunk_boundary_bridge_to_state": debug_info.get("chunk_boundary_bridge_to_state"),
                    "action_names": list(action_feature_names),
                    "obs_state": obs_state_vector,
                    "state_before_send": state_before_send_vector,
                    "raw_action0": raw_action0_vector,
                    "executed_action0": executed_action0_vector,
                    "previous_overlap_action0": previous_overlap_action0_vector,
                    "robot_action_to_send": robot_action_to_send_vector,
                    "sent_action": sent_action_vector,
                    "obs_to_before_send": vector_distance(obs_state_vector, state_before_send_vector),
                    "raw_action0_to_obs": vector_distance(raw_action0_vector, obs_state_vector),
                    "executed_action0_to_obs": vector_distance(executed_action0_vector, obs_state_vector),
                    "previous_overlap_action0_to_obs": vector_distance(
                        previous_overlap_action0_vector, obs_state_vector
                    ),
                    "robot_action_to_send_to_obs": vector_distance(robot_action_to_send_vector, obs_state_vector),
                    "sent_action_to_obs": vector_distance(sent_action_vector, obs_state_vector),
                }
                if include_action_chunks:
                    raw_chunk = tensor_to_action_sequence(debug_info.get("raw_chunk"))
                    executed_chunk = tensor_to_action_sequence(debug_info.get("executed_chunk"))
                    previous_overlap_chunk = tensor_to_action_sequence(debug_info.get("previous_overlap_chunk"))
                    debug_row.update(
                        {
                            "raw_chunk": raw_chunk,
                            "executed_chunk": executed_chunk,
                            "previous_overlap_chunk": previous_overlap_chunk,
                            "raw_chunk_to_obs": vector_distances(raw_chunk, obs_state_vector),
                            "executed_chunk_to_obs": vector_distances(executed_chunk, obs_state_vector),
                            "previous_overlap_chunk_to_obs": vector_distances(
                                previous_overlap_chunk, obs_state_vector
                            ),
                        }
                    )
                write_action_state_debug(debug_row)

            if dataset is not None:
                action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
                frame = {**observation_frame, **action_frame, "task": single_task}
                dataset.add_frame(frame)

            if display_data:
                log_rerun_data(
                    observation=obs_processed, action=action_values, compress_images=display_compressed_images
                )

            dt_s = time.perf_counter() - start_loop_t
            sleep_time_s: float = 1 / fps - dt_s
            if sleep_time_s < 0:
                logging.warning(
                    f"Record loop is running slower ({1 / dt_s:.1f} Hz) than the target FPS ({fps} Hz). Dataset frames might be dropped and robot control might be unstable. Common causes are: 1) Camera FPS not keeping up 2) Policy inference taking too long 3) CPU starvation"
                )

            precise_sleep(max(sleep_time_s, 0.0))

            debug_frame_index += 1
            timestamp = time.perf_counter() - start_episode_t

    finally:
        if action_state_debug_fh is not None:
            logging.info("[ActionStateDebug] Closed action_state_debug.jsonl")
            action_state_debug_fh.close()


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(action=robot.action_features),
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    dataset = None
    listener = None

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        robot.connect()
        if teleop is not None:
            teleop.connect()

        listener, events = init_keyboard_listener()

        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    display_compressed_images=display_compressed_images,
                )

                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)

                    if robot.name == "unitree_g1":
                        robot.reset()

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        control_time_s=cfg.dataset.reset_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                    )

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    continue

                dataset.save_episode()
                recorded_episodes += 1
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            dataset.finalize()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if listener and hasattr(listener, "stop") and not is_headless():
            listener.stop()

        if cfg.dataset.push_to_hub:
            if dataset is not None:
                dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
